name: "AppImage"
description: "Builds a Linux AppImage on Debian 10 (Buster)"
inputs:
  executable:
    description: "Executable file to package into an AppImage."
    required: true
  icon-file:
    description: "Icon file to use for the AppImage."
    required: true
  desktop-file:
    description: "Desktop file to use for the AppImage."
    required: true
  appdir:
    description: "Path to use for the AppImage filesystem."
    required: true

runs:
  using: composite

  steps:
    - name: Build packetry-x86_64.AppDir (Linux)
      shell: bash
      run: |
        DEPLOY_GTK_VERSION=4 linuxdeploy-x86_64.AppImage \
          --appimage-extract-and-run \
          --appdir ${{ inputs.appdir }} \
          --executable=${{ inputs.executable }} \
          --icon-file ${{ inputs.icon-file }} \
          --plugin gtk \
          --desktop-file ${{ inputs.desktop-file }}

    - name: Shrink packetry-x86_64.AppDir (Linux)
      shell: bash
      run: |
        # cd to AppDir lib directory
        cd $GITHUB_WORKSPACE/${{ inputs.appdir }}/usr/lib

        # remove any system libraries we don't want to include in case
        # of conflicts with a user's system
        rm -f libX*
        rm -f libblkid*
        rm -f libbsd*
        rm -f libpixman*
        rm -f libxcb-render*
        rm -f libzstd*

        # add libharfbuzz even though we don't link to it directly as
        # some systems will attempt to dlopen(3) its own version if it
        # is not present
        cp -a /opt/gtk-*/lib/x86_64-linux-gnu/libharfbuzz.* .
        cp -a /opt/gtk-*/lib/x86_64-linux-gnu/libharfbuzz-gobject.* .
        cp -a /opt/gtk-*/lib/x86_64-linux-gnu/libharfbuzz-icu.* .
        cp -a /opt/gtk-*/lib/x86_64-linux-gnu/libharfbuzz-subset.* .

        # remove duplicate library files and replace with symlinks
        fdupes --sameline --order=name . | while read -r lib ; do
            src=$(echo $lib | rev | cut -d' ' -f1 | rev)
            dupes=$(echo $lib | rev | cut -d' ' -f2- | rev)
            rm $dupes
            for dst in $dupes ; do
                ln -s $src $dst
            done
        done

        # strip all libraries
        strip ./lib*.*

        # return to workspace directory
        cd $GITHUB_WORKSPACE

    - name: Gather licenses (Linux)
      shell: bash
      run: |
        # cd to AppDir /usr/share/doc directory
        cd $GITHUB_WORKSPACE/${{ inputs.appdir }}/usr/share/doc

        # remove any licenses for system libraries we don't distribute
        rm -rf libblkid1
        rm -rf libbsd0
        rm -rf libxau6
        rm -rf libxcb-render0
        rm -rf libxcursor1
        rm -rf libxdamage1
        rm -rf libxdmcp6
        rm -rf libxext6
        rm -rf libxfixes3
        rm -rf libxi6
        rm -rf libxinerama1
        rm -rf libxrandr2
        rm -rf libxrender1
        rm -rf libzstd1

        # Return to workspace directory
        cd $GITHUB_WORKSPACE

    - name: Convert icon to application/x-executable on all themes (Linux)
      shell: bash
      run: |
        cp /dev/null ${{ inputs.appdir }}/usr/share/icons/hicolor/512x512/apps/$(basename ${{ inputs.icon-file }})

    - name: Build packetry-x86_64.AppImage (Linux)
      shell: bash
      run: |
        appimagetool-x86_64.AppImage \
          --appimage-extract-and-run \
          ${{ inputs.appdir }}/
